# Generated by Django 2.1.11 on 2019-08-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UUID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
